checks:
    php:
        code_rating: true
        duplication: true
filter:
    excluded_paths:
        - tests/*
build:
    tests:
        override:
            - command: ./vendor/bin/phpunit --verbose --coverage-clover=coverage.xml
              coverage:
                  format: php-clover
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run