language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3

dist: trusty
sudo: false

before_script:
    - composer self-update
    - composer install --no-interaction --dev

script: ./vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

matrix:
    fast_finish: true